### ISSUE TITLE
Almanax bonus message with ingame date and meridia description

### ISSUE THREAD

**Issue by Markkop** [Markkop/corvo-astral#8]
Similar to [Wakmanax](https://github.com/elio-centrique/wakmanax/blob/master/wakmanax.js), it would be cool to have the current ingame date and a meridia description when showing the current almanax bonus.

http://www.krosmoz.com/en/almanax/

**Comment by Vertylo** [comment]
Hi, you will have some "issues" with this part. There is currently no translation of the meridia except in French and English...

**Comment by Markkop** [comment]
Indeed. It would be possible to automate some kind of translator, but that might end up with some low quality translation.
Perhaps keeping them in english would be enough.
Are you the author of http://almanax.kasswat.com/ ?

**Comment by Vertylo** [comment]
Keeping english version is probably the best option... And yes, I'm the author, I made it for my own discord bot.

**Comment by Markkop** [comment]
Accomplished with #15, #16 and #17
There are still some improvements, like caching the scrapping data and config options to customize the Almanax feature.
Thanks Vertylo and the creator of Wakmanax for the inspiritation :D
