### ISSUE TITLE
new and improved translations

### ISSUE THREAD

**Issue by Markkop** [Markkop/corvo-astral#9]
We have several translations mispelled and lacking others.
Feel free to add or change some through a Pull Request

You can check them here: https://github.com/Markkop/corvo-astral/blob/master/src/stringsLang.ts

**Comment by SantiagoJimenezQ** [comment]
Hi, @Markkop, I'm a native Spanish speaker, I've fixed some spelling mistakes. #11

**Comment by SantiagoJimenezQ** [comment]
Btw, it seems like this repository is not eligible for Hacktoberfest; could you fix that? 😅 
<img width="507" alt="Screenshot 2020-10-04 at 12 02 54" src="https://user-images.githubusercontent.com/45161981/95012590-2e531a00-063a-11eb-8c3f-b1294be56e65.png">
<img width="679" alt="Screenshot 2020-10-04 at 12 02 58" src="https://user-images.githubusercontent.com/45161981/95012592-2f844700-063a-11eb-9c40-67b281da67f6.png">

**Comment by Markkop** [comment]
@SantiagoJimenezQ Thanks for contributing!
Oh, I didn't know I had to enable it.
Can you check if the Pull Request is now counting up to Hacktoberfest?
If not, feel free to open a new one :rocket:

**Comment by SantiagoJimenezQ** [comment]
Yes, now it is counting up for Hacktoberfest. Thanks! 🥳

**Comment by Markkop** [comment]
Thank you guys!
